(define (vector->@vector vec)
  (let* ((len (vector-length vec))
         (result (make-@vector len)))
    (let loop ((i 0))
      (unless (= i len)
        (@vector-set result i (vector-ref i))
        (loop (+ i 1))))
    result))

(define (@vector->vector @vec)
  (let* ((len (@vector-length @vec))
         (result (make-vector len)))
    (let loop ((i 0))
      (unless (= i len)
        (vector-set result i (@vector-ref i))
        (loop (+ i 1))))
    result))

